import { FQA as FQAComponent } from "../src/Components";
import Head from "next/head";

function FQA() {
  return (
    <>
      <Head>
        <title>Preguntas Frecuentes 🚘</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <FQAComponent />
    </>
  );
}

export default FQA;
