import Head from "next/head";
import { formatCardsCar } from "../src/utils";
import api from "../src/api";
import {
  Header,
  FeaturedSection,
  BenefitsSection,
  StepsSection,
  WhyBuySection,
  StillHaveDoubts,
  OurBlogSection,
  ACategoryForYourNeed,
} from "../src/Components";

function Home({ data, postInfo }) {
  return (
    <>
      <Head>
        <title>Connect Car 🚗</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <FeaturedSection />
      <BenefitsSection />
      <StepsSection />
      <WhyBuySection cars={data} />
      <ACategoryForYourNeed />
      <OurBlogSection postInfo={postInfo} />
      <StillHaveDoubts />
    </>
  );
}

Home.getInitialProps = async () => {
  try {
    const res = await api.get(
      "organization-vehicles?sort=random&populate=true&limit=2",
    );
    const res2 = await api.get("blogPosts", {
      limit: 1,
      skip: 0,
      order: "createdAt",
      sort: "desc",
    });
    const data = res2?.data?.data?.[0];
    const postInfo = {
      slug: data.postId ?? "",
      title: data.title,
      description: data.content
        .slice(0, 220)
        .replace(/(<([^>]+)>)|[^a-zA-Z0-9,:;\-.?!áéíóúüñ\s]/gi, ""),
      imageUrl: data.imageUrl,
    };
    const cars = res?.data?.data;
    return {
      data: cars?.map(formatCardsCar),
      postInfo,
    };
  } catch (e) {
    console.trace(e);
    return { data: [] };
  }
};

export default Home;
