import Head from "next/head";
import { Us as UsComponent } from "../src/Components";

function Us() {
  return (
    <>
      <Head>
        <title>Nosotros 🚘</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <UsComponent />
    </>
  );
}

export default Us;
